const contractAddress = "0xa5A315ED0cE5c9C0fA099a7f3809112eE760FFee"; // Replace with your own contract address
const chain = 'goerli'; // goerli, polygon, or ethereum

const welcome_h1 = "Welcome to the AnonymousPixls NFT Project!!";
const welcome_h2 = "Connect to MetaMask to Get Started";
const welcome_p = 'AnonymousPixls is a unique collection of 5000 pixelated characters which are decentralized digital assets on the polygon blockchain that will gain value in the long term';
const h1_presale_coming_soon = "NFT Drop Coming Soon!!";
const h1_presale_mint = "Pre-Sale Minting Open!!";
const h1_public_mint = "Public Minting Open!!";
const h2_presale_coming_soon = "Pre-Sale Minting Countdown";
const h2_presale_mint = "Public Minting Countdown";
const p_presale_coming_soon = "We are working hard to launch the NFT Collection. Stay tuned for updates!";
const p_presale_mint_not_whitelisted = "You are not whitelisted for the pre-sale.. 😢";
const p_presale_mint_whitelisted = "You're on the whitelist for the pre-sale! 🎉";
const p_presale_mint_already_minted = "You've already claimed your whitelist mint. Thank you! 🎉";
const p_public_mint = "Public minting is now open everyone can mint";
const button_presale_coming_soon = "Get on the Whitelist";
const button_presale_mint_whitelisted = "Mint Your NFT";
const button_presale_mint_not_whitelisted = "Get on the Whitelist";
const button_presale_already_minted = "Join The Pixls Family";
const button_public_mint = "MINT";
const mint_failed = "You couldn't mint your nft";
